# Generated by Django 5.1.5 on 2025-02-03 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShadowLock', '0006_alter_environment_shared_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='Environment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='Passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
